### ISSUE TITLE
Can we use Jade(Pug) as the template engine to create this invoice ?

### ISSUE THREAD

**Issue by chanakaDe** [Geexteam/proto-node-pdf#1]
You have used 'handlebars' as the template engine. It's fine.
Is it ok to use Pug to make this invoice ? I mean all the fields and data table ?
Then we can use a for loop like something and populate the data table. 
Is that possible ?

**Comment by chanakaDe** [comment]
@Geex-Renzo  You there ?

**Comment by CherryNerd** [comment]
Of course you can, I usually use EJS myself so there is no problem there at all.
Just switch Handlebars out with whatever you want and keep the PDF generation intact ;)

**Comment by chanakaDe** [comment]
@Geex-Renzo thanks buddy. you saved me.... I worked hard a lot. I have used Jasper Reports earlier. Anyway this is more easier than it. Because we can use HTML based languages. 
Do you have a startup ? I'm a 3rd year Software Engineering student from University of Westminster, UK.
It's a pleasure to meet you. These days i'm working hard for GSOC 2017 :+1:

**Comment by CherryNerd** [comment]
You're welcome!
Back when I really needed this, it took me a while to figure out as well, so what harm is there helping the community ;)
We're based in The Netherlands and yes, pleased to meet you too!

**Comment by chanakaDe** [comment]
@Geex-Renzo  Yeah it's really great to share what you found and what you have when others need this. Love open source :) And also do you have a startup ? Are you working on projects ? I am working on a open source accounting system. Alternative to QuickBooks. 
chanu1993@gmail.com is my email. Please say hello. I will show you more.

**Comment by CherryNerd** [comment]
We are currently working on an open Source CMS which is almost ready to be launched.
From this CMS we are going to create a development Framework.
You can follow us on Twitter on [@GeeX_Dev](https://twitter.com/GeeX_dev)
If you'd like, we can talk there so we can close this issue ;)
